name: Pull Request Labeler
description: Labels pull requests based on the base branch
branding:
  icon: tag
  color: blue
inputs:
  token:
    description: The GITHUB_TOKEN secret
    required: true

runs:
  using: composite
  steps:
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Get the PyGithub module
      run: pip install PyGithub
      shell: bash

    - name: Label the PR (if needed)
      run: ${{ github.action_path }}/github-labeler.py
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        PR_NUM: ${{ github.event.number }}
